### PR TITLE
remove unsupported @mention name from Hipchat bot

### PR DESCRIPTION
**Pull request by glower**
removed `mentionName` from hipchat bot, it was not used correctly

### CODE REVIEW

**Comment by glower** [comment]
was fast :)

**Comment by rusenask** [comment]
please make circleci happy as well :)

**Comment by glower** [comment]
done

**Comment by glower** [comment]
we have keel now running in our cluster so I can test hipchat integration, maybe we will find some other bugs

**Comment by glower** [comment]
please don't megre now, found another bug in hipchat configuration

**Comment by glower** [comment]
can be merged, looks good now

**Comment by rusenask** [comment]
release tagged, should be ready when dockerhub finishes it, thanks!

**Pull request merged**
