### PR TITLE
move slack related bot code to a sub module

### PR DESCRIPTION
**Pull request by glower**
just moved all the slack bot code to the submodule. I tried to do it like in the notification module with minimal effort. Just throw it away if you dont like it, it's ok :)

### CODE REVIEW

**Comment by rusenask** [comment]
looks great! is this ready for merging? I could create an alpha image from and would want to play around with it.

**Comment by glower** [comment]
Cool! Yes, it is ready for merging. I totally forgot that I already put my WIP on HipChat integration in the same PR. I will first stop to work on this branch :) 
Need to say, Slack API is so much better, to have interaction with HipChat I need to use XMPP chat, so nothing fancy with Websockets :)

**Comment by glower** [comment]
thx that you have time for this!

**Comment by rusenask** [comment]
Well, slack is not that great as well. Some functionality is only available through their HTTP API and not websockets so you end up using both.. :) thank you for your contributions! I hope we could add rocket chat as well, it looks like a nice open source slack clone.

**Comment by glower** [comment]
I will finalise HipChat integration in the next PR and I can have a look into rocket chat :)

**Comment by rusenask** [comment]
Added one commit into master branch as the tests were not compiling, otherwise it looks awesome :) Regarding rocketchat, even though I heard it's used a lot, there were no requests to add it yet :| 

As for this hipchat bot, it would be nice to have some kind of matrix of supported commands. 
Current slack bot can:
- list approvals, approve, reject
- list deployments
- help message

**Pull request merged**
