### PR TITLE
adds NOTIFICATION_LEVEL environment variable

### PR DESCRIPTION
**Pull request by gillesdemey**
Adds support for the NOTIFICATION_LEVEL environment variable to configure notifications

### CODE REVIEW

**Comment by rimusz** [comment]
Can you please also bump the chart version?
Also can you run `make gen-deploy` so the new kubernetes templates (used the kubectl ... way) get generated as well.
thanks

**Comment by rimusz** [comment]
yes, I forgot the `values.yaml` file to mention, and also in https://github.com/keel-hq/keel/blob/master/chart/keel/README.md#configuration

**Comment by gillesdemey** [comment]
done, PTAL :)

**Comment by rimusz** [comment]
I made in the PR some naming changes so are in good practices with `yaml` variables naming

**Pull request merged**
