### PR TITLE
fix(helm): run keel with created serviceaccount and not as cluster-admin

### PR DESCRIPTION
**Pull request by ghouscht**
See Issue #571 for details

### CODE REVIEW

**Comment by ghouscht** [comment]
Hmm the ci failure does not seem relevant to my changes:

```
Error: Looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
Error linting charts
```

**Comment by rusenask** [comment]
could you please bump chart version too https://github.com/keel-hq/keel/blob/master/chart/keel/Chart.yaml#L4? it will auto-release on merge

**Comment by ghouscht** [comment]
Sure, increased the patch release by one, the chart linter still fails though.

**Comment by rusenask** [comment]
I will have a look at it a bit later today, I think it's a changed endpoint as per https://stackoverflow.com/questions/65407317/helm-init-failed-is-not-a-valid-chart-repository-or-cannot-be-reached-failed-to

**Comment by ghouscht** [comment]
Got it to work with ct/helm v3, probably the easiest option, since helm v2 is "legacy"

**Comment by rusenask** [comment]
nice!

**Comment by cagataygurturk** [comment]
Hi, 

This is a breaking change, I think it should have been a minor version bump:

`cannot patch "keel" with kind ClusterRoleBinding: ClusterRoleBinding.rbac.authorization.k8s.io "keel" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"keel"}: cannot change roleRef`

**Pull request merged**
