### PR TITLE
Update ingress chart definition

### LINKED ISSUE #635: helm chart uses outdated API version for ingress and should support ingressClassName
```
W0909 09:08:48.099861  299554 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0909 09:08:48.128581  299554 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W0909 09:08:48.245069  299554 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

This is from:

```
# Source: keel/charts/keel/templates/ingress.yaml
apiVersion: extensions/v1beta1
```

Also it looks like the ingress chart doesn't support the `ingressClassName` which is required for ingress-nginx 4.0

https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

Here is the change that is required to do that:

https://github.com/longhorn/longhorn/pull/2258/files

### PR DESCRIPTION
**Pull request by brianmay**
Closes #635

### CODE REVIEW

**Comment by brianmay** [comment]
If there is anything else I need to change release, please let me know.

**Comment by brianmay** [comment]
The lint check seemed to require I update the chart version, so I did that.

**Comment by NicolasLemince** [comment]
@rusenask can we merge ? It is an essential update...

**Comment by rusenask** [comment]
yes, sorry for the delay!

**Pull request merged**
