### PR TITLE
fix match tag during versionned update

### LINKED ISSUE #212: on a force + match-tag setting, valid semver pushes will still be deployed
For us this is nice because it means that any prod tag will reset our dev envs, but it's not really intended.

we could may be make it an option with: 
 * `keel.sh/match-tag: "true"` only deploy matching tags
 * `keel.sh/match-tag: "allow-valid-semver"` force match tag + deploy also on valid semver

### PR DESCRIPTION
**Pull request by azr**
howdy, this should fix #212 for now

### CODE REVIEW

**Comment by rusenask** [comment]
Hi! Thanks, looks good! :) two test cases probably explain a lot better this situation than the issue :D

**Comment by azr** [comment]
yeah :D

**Comment by azr** [comment]
can we please tag this for release ? that'd be awesum :D may be you want to test it first ?

**Comment by rusenask** [comment]
did it work for you?

**Comment by azr** [comment]
... tests said so lol 😄

**Comment by azr** [comment]
thankkkssss !!

**Pull request merged**
