### PR TITLE
deploy matching tags with "keel.sh/match-tag" annotations

### PR DESCRIPTION
**Pull request by azr**
Hi there !

This should be a better & simpler approach for `match-tag` than #189

### CODE REVIEW

**Comment by azr** [comment]
Not sure if this is doable in the helm provider though because I can't find a spot where we can read annotations.

**Comment by rusenask** [comment]
Hi! looks great :) will sort out helm provider myself, no worries :) Would you want an image tagged with current changes?

**Comment by azr** [comment]
Nice ! ok. Hm, I can wait, no worries.

**Comment by azr** [comment]
Nice ! sveikata !

**Comment by rusenask** [comment]
:D I sveikata!

**Pull request merged**
