### PR TITLE
Add generic ingress

### PR DESCRIPTION
**Pull request by botzill**
Here I added generic ingress. 

@boxrick I did make modifications for the PR you posted. Can you take a look and see if you will work in your case as well?

Note that I did remove `kubernetes.io/ingress.allow-http: "{{- .Values.gcloudIngress.allowHttp }}"` as now you can add that via ingress.annotations with no issue. 

This version is more generic and will work for more cases. 

Thx, hope this is helpful.

### CODE REVIEW

**Comment by botzill** [comment]
Hi @boxrick @rusenask.

Can you take a look, please, at this PR and see if it's OK?


Thx!

**Comment by botzill** [comment]
Hi. Any chance we can take a look at this? @rusenask

**Comment by rusenask** [comment]
hey @botzill  if this works for you, I can merge it.

**Comment by botzill** [comment]
Hi @rusenask, sure works for me. Hopefully will work as well for @boxrick

**Comment by boxrick** [comment]
I will test this later and feedback here.

**Comment by botzill** [comment]
Thx @boxrick, let me know if works OK.

**Comment by rusenask** [comment]
@botzill can you please bump the chart version and let's merge it :)

**Comment by botzill** [comment]
@rusenask done.

**Comment by rusenask** [comment]
well, that linter is never happy :D

**Pull request merged**
