### PR TITLE
ShouldUpdate now makes sure pre-releases match + tests

### LINKED ISSUE #63: util/version: pre-release tags are not taken in to consideration in ShouldUpgrade()
In my organization we're working on using SemVer for all of our releases, with the use of pre-release tags to test experimental builds. For pre-release builds, we increment the patch and then add the pre-release information at the end. So if `v1.2.2` is the last tag, the pre-release would be `v1.2.3-preNNNNNN`.

The problem is that `keel` does not currently inspect the information about the PreRelease to understand whether it's a "proper release"[1]. This means that if you have your policy set to `patch`, a pre-release of the next patch version will be deployed. To give a quick overview with each policy type there is a different combination of pre-release tags which someone may want to deploy:

* `v1.2.2` => `v1.2.3-pre`
* `v1.2.3` => `v1.3.0-pre`
* `v1.2.3` => `v2.0.0-pre`
* `v1.2.3-pre` => `v1.3.0-pre`
* `v1.2.3-pre` => `v1.3.0`

Attached to the bottom of this issue is a patch with a unit test showing the failure mode that made me realize this was a potential issue. [2]

To solving the problem, it seems there are two ways to solve this problem within keel:

* Add more policies (e.g., `PolicyTypePatchPreRelease`, `PolicyTypeMinorPreRelease`, etc.) and do the additional checks
* Introduce a `prelreasePolicy` value that can contain the same values as `policy` does now (and maybe rename `policy` to `releasePolicy`). We could then have a matrix of behaviors based on the releasePolicy and the prereleasePolicy.

The second approach feels like the most powerful, and could allow you to do something like have a `releasePolicy: minor` so you get all of the minor + patch updates, but a `prereleasePolicy: patch` so that you only run experimental patch builds. This might be useful for something like a QA environment.

I think one of the easier ways to tackle this, since it's already a numerical value, to use it as bitwise flags. Policies could then be created by doing something like `types.PolicyTypePreReleasePatch & types.PolicyTypeMinor`. I'd be happy to take on implementing it once a good design is figured out.

[1] I quote proper release, because this could be up to who you ask.
[2]
```diff
diff --git a/util/version/version_test.go b/util/version/version_test.go
index f3c7d68..d172f8f 100644
--- a/util/version/version_test.go
+++ b/util/version/version_test.go
@@ -173,6 +173,16 @@ func TestShouldUpdate(t *testing.T) {
 			wantErr: false,
 		},
 		{
+			name: "patch pre-release, policy patch",
+			args: args{
+				current: &types.Version{Major: 1, Minor: 4, Patch: 5},
+				new:     &types.Version{Major: 1, Minor: 4, Patch: 6, PreRelease: "pre-20170728121212"},
+				policy:  types.PolicyTypePatch,
+			},
+			want:    false,
+			wantErr: false,
+		},
+		{
 			name: "patch increase, policy ptach",
 			args: args{
 				current: &types.Version{Major: 1, Minor: 4, Patch: 5},

```

### LINKED ISSUE #182: Staging/acceptance/prod & versionning
Hi there,

I have a staging/acceptance/production setup.
I would like to be able to update all of their deploys independently depending on when I push to  feature branch/master branch/tag respectively.

But I have to ask what would work and may be it would be nice if this would be documented somewhere.

Here's a few ideas:

1. Differenciating with special tag ( or pre-release tag ) ?

staging deploy : `docker.com/this/that:latest-staging`

acc : `docker.com/this/that:latest-acceptance`

prod `docker.com/this/that:latest`

if I do this with a force `force` setting for all deploys, will a docker push to `image.com:latest-staging`  also trigger a deploy for my prod deployment ?

2. Differenciating with image name ?

staging deploy : `docker.com/this/that-staging:latest`

acc : `docker.com/this/that-acceptance:latest`

prod `docker.com/this/that:latest`

I kinda don't like this ? But is this the only working solution now ? If yes may be I will try to have solution 1 work by doing a P.R. if you agree :)

### PR DESCRIPTION
**Pull request by azr**
There, simple than expected

this should also
fix #63
fix #182

### CODE REVIEW

**Comment by azr** [comment]
I only have launched the tests locally, will try in a cluster

**Comment by azr** [comment]
Doesn't work for me 
```
➜  keel git:(master) go build ./cmd/keel
➜  keel git:(master) ✗ keel --no-incluster
INFO[0000] extension.notification: sender registered     name=hipchat
INFO[0000] extension.notification: sender registered     name=mattermost
INFO[0000] extension.notification: sender registered     name=slack
INFO[0000] extension.notification: sender registered     name=webhook
INFO[0000] bot: registered                               name=slack
INFO[0000] keel starting...                              arch=amd64 build_date= go_version=go1.10.1 os=darwin revision= version=
ERRO[0000] provider.kubernetes: failed to create kubernetes client  error="No Auth Provider found for name \"gcp\""
FATA[0000] main: failed to create kubernetes implementer  config="&{false /Users/azr/.kube/config }" error="No Auth Provider found for name \"gcp\""
➜  keel git:(master) ✗ kubectl get pods -n keel
NAME                    READY     STATUS    RESTARTS   AGE
keel-7dbf9bbc8f-2lkvc   1/1       Running   0          2d
➜  keel git:(master) ✗
```

**Comment by rusenask** [comment]
yeah, I noticed that on GKE it kubeconfig doesn't work for client-go, it did work on minikube and docker with k8s for macos. I will try it in the evening, have to run too :)

**Comment by azr** [comment]
Oh nice, so this works !? Cool.

Also will a `latest-staging` tag match only for `-staging` prereleases ?

**Comment by rusenask** [comment]
Yes, it does work :) `latest-staging` will work just fine but only with `force` policy, because it's a string and not a version. `latest` would only subscribe to `latest` and `latest-staging` would only subscribe to `latest-staging` :) 
With metadata on semver we can do now:
`1.0.2-staging` -> `1.0.3-staging` if policy is patch, same for minor and major versions which is cool. Thanks for this! :)

**Comment by azr** [comment]
Awesome 👍

**Pull request merged**
