### PR TITLE
Azure registry webhooks support 

### LINKED ISSUE #196: Support azure container registry webhooks

### PR DESCRIPTION
**Pull request by alonisser**
Support azure container registry webhooks . close #196

### CODE REVIEW

**Comment by alonisser** [comment]
I understand the docs are in another repo, if this would be considered I'll make a PR there also to add azure webhooks to the docks

**Comment by rusenask** [comment]
Ahh, made my day! :) Thanks, looks really great!

**Comment by alonisser** [comment]
Hey, please verify I wrote this correctly.. my first golang code ever (I adapted the tests from the quay example)

**Comment by rusenask** [comment]
I will give it a field test but it does look correct from the test. Good job!

**Pull request merged**
