### PR TITLE
Add Image Pull Secrets to Deployment Template

### PR DESCRIPTION
**Pull request by gelugu**
This feature allows specifying image pull secrets in the `values.yaml` file, which are then used in the `deployment.yaml` file to pull images from private registries.

The change is backward compatible and follows the existing code style.

Changes include:

- Modified `values.yaml` to include `imagePullSecrets` as a list of secrets.
- Updated `deployment.yaml` to include `imagePullSecrets` under `spec.template.spec`. The `imagePullSecrets` field is only presented if at least one secret is defined.
- Updated the `README.md` file to include the new `imagePullSecrets` configuration option.

Please review and provide any feedback.

### CODE REVIEW

**Comment by gelugu** [comment]
@rusenask hi! Could you please review these changes?

**Comment by david-garcia-garcia** [comment]
@gelugu this change only allows to pull the KEEL image itself from a private registry, but it's not about supporting having private registries in the actual workloads?

**Comment by gelugu** [comment]
@david-garcia-garcia hi!
We can rewrite `image.repository`:
```
image:
  repository: our.private.registry/keelhq/keel
```
But we need to specify `imagePullSecrets`.

**Comment by gelugu** [comment]
@david-garcia-garcia, sorry, I did not understand the question at first. Yes, we only need to pull the KEEL image from private registries.

**Comment by gelugu** [comment]
@david-garcia-garcia hi! can you please review this PR? it seems like a small change, but would really help us to move on with our security tasks

**Comment by stieler-it** [comment]
This would be helpful to run keel in airgapped enviroments (with the provided Helm Chart)

**Comment by david-garcia-garcia** [comment]
@gelugu I absorbed your PR as part of an initial micro refactor. Can you please test new Helm Chart release? Note that the URL for the helm repository has changed:

```
  repository = "https://keel-hq.github.io/keel"
  chart      = "keel"
  version    = "v1.0.4"
```

**Comment by gelugu** [comment]
I've checked and everything is working. Thnx!

**Pull request closed without merging**
