### PR TITLE
Add option for additional containers to be run with Helm chart

### PR DESCRIPTION
**Pull request by nbjohnson**
Adds option to run additional containers alongside Keel in Helm deploy

### CODE REVIEW

**Comment by nbjohnson** [comment]
Should I bump the chart version? Or is that for a maintainer to chose what version to change it to?

**Comment by rusenask** [comment]
yes, chart version should be bumped. What's the use case for this?

**Comment by nbjohnson** [comment]
The use case for allowing other containers to run alongside Keel at least for me is to have oauth2proxy to be run cleanly for security. I know there is a feature in works that will allow for the ui to be run without the username/password and while I can't wait for that to be completed, at least for now I do need a way to cleanly run oauth2proxy for multi-user security in front of Keel.

**Comment by nbjohnson** [comment]
@rusenask Thanks for the merge, do you know when I could expect that change to be propagated to the helm release so I can install v0.9.9 of the chart?

**Comment by rusenask** [comment]
chart is built on merge, it should be there :)

**Comment by nbjohnson** [comment]
Hmm, when I add the keel helm repo and do `helm search repo keel` I see `keel/keel 0.9.8 0.16.1`, it doesn't list a v0.9.9 for the chart

**Comment by rusenask** [comment]
I see, helm chart build is failing due to a checksum mismatch, I will see what's up this evening

**Comment by nbjohnson** [comment]
@rusenask Any update on when the build issues might be resolved?

**Pull request merged**
