### PR TITLE
chore: remove refs to deprecated io/ioutil

### PR DESCRIPTION
**Pull request by david-garcia-garcia**

### CODE REVIEW

**Comment by joebowbeer** [comment]
@david-garcia-garcia Why no reviewers? Is the master branch not protected?

**Comment by joebowbeer** [comment]
@rusenask sure, if it would be helpful.

@david-garcia-garcia thoughts?

**Comment by david-garcia-garcia** [comment]
@joebowbeer it makes sense we have a minimum protection workflow as long as there is commitment/availabilty and this does not represent a bottleneck. Minimum would be to require a PR (I think I did at least one super minor direct commit to master without PR). But if this hinders further development it might be more damaging to the project than reducing the contribution barrier.

**Comment by joebowbeer** [comment]
@david-garcia-garcia The Contributing doc currently says "We use pull requests"

https://github.com/keel-hq/keel?tab=readme-ov-file#contributing

I suggest updating the Contributing section if there are any changes.

Also, I think it would be a good idea to announce any changes in procedure to the keel channel in kubernetes slack:

https://kubernetes.slack.com/archives/C6JDWE7M2

**Pull request merged**
